Repository snek-at/ops-front, pull requests merged in 2020-08, with the labels that each got.

#8 Add nav storage aa1 to implement 1
  src/components/molecules/SideNav/index.jsx
  src/components/pages/AdminPage/index.jsx
Labels: enhancement

#9 Add pages ba1 to implement 1
  .vscode/settings.json
  package.json
  src/components/molecules/SideNav/sidenav.scss
  src/components/organisms/index.js
  src/components/organisms/sections/Page/index.jsx
  src/components/organisms/sections/Page/page.scss
  src/components/organisms/sections/Pipelines/index.jsx
  src/components/organisms/tabs/PageImprint/index.jsx
  src/components/organisms/tabs/PageOverview/index.jsx
  src/components/organisms/tabs/PageOverview/pageoverview.scss
  src/components/organisms/tabs/PageProjects/index.jsx
  src/components/organisms/tabs/PageProjects/pageprojects.scss
  src/components/organisms/tabs/PageUsers/index.jsx
  src/components/organisms/tabs/PageUsers/pageusers.scss
  src/store/actions/pageActions.js
  src/store/reducers/pageReducer.js
  src/utilities/_base.scss
Labels: bug, enhancement

#10 Add userprofile aa1 to implement 1
  src/components/organisms/index.js
  src/components/organisms/sections/Page/index.jsx
  src/components/organisms/sections/User/index.jsx
  src/components/organisms/sections/User/user.scss
  src/components/organisms/tabs/PageUsers/index.jsx
  src/components/pages/AdminPage/index.jsx
  src/store/actions/pageActions.js
  src/store/reducers/pageReducer.js
Labels: enhancement

#13 Add gitlabs aa1 to implement 1
  src/components/atoms/AIInput/index.jsx
  src/components/atoms/AIToggle/index.jsx
  src/components/atoms/index.js
  src/components/organisms/index.js
  src/components/organisms/sections/GitLabs/index.jsx
  src/components/organisms/tabs/PageImprint/index.jsx
  src/components/organisms/tabs/PageOverview/pageoverview.scss
  src/components/pages/AdminPage/index.jsx
  src/index.js
  src/store/actions/gitlabActions.js
  src/store/reducers/connectorReducer.js
  src/store/reducers/gitlabReducer.js
  src/store/reducers/pageReducer.js
  src/store/reducers/permissionReducer.js
  src/store/reducers/pipelineReducer.js
  src/utilities/_base.scss
Labels: enhancement

#14 Add connectors aa1 to implement 1
  src/components/organisms/index.js
  src/components/organisms/sections/Connectors/index.jsx
  src/components/pages/AdminPage/index.jsx
  src/store/actions/connectorActions.js
  src/store/actions/gitlabActions.js
Labels: enhancement

#15 Add permissions aa1 to implement 1
  src/components/atoms/AIInput/index.jsx
  src/components/organisms/index.js
  src/components/organisms/sections/GitLabs/index.jsx
  src/components/organisms/sections/Permissions/index.jsx
  src/components/organisms/sections/Permissions/permissions.scss
  src/components/pages/AdminPage/index.jsx
  src/store/actions/connectorActions.js
  src/store/actions/permissionActions.js
Labels: enhancement

#16 Update coc aa1 to master (Update CODE_OF_CONDUCT.md)
  CODE_OF_CONDUCT.md
Labels: documentation

#18 Update cont aa1 to master (Update CONTRIBUTING.md)
  CONTRIBUTING.md
Labels: documentation

#19 Update pr aa1 to master (Update PULL_REQUEST_TEMPLATE)
  PULL_REQUEST_TEMPLATE
Labels: documentation

#20 Update readme aa1 to master (Update README.md)
  README.md
Labels: documentation

#21 Update bug report aa1 to master (Update bug_report.md)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#22 Update tastic feature request aa1 to master (Update tastic_feature_request.md)
  .github/ISSUE_TEMPLATE/tastic_feature_request.md
Labels: documentation

#24 Add login aa1 to implement 1
  src/Routes.js
  src/components/molecules/SideNav/index.jsx
  src/components/organisms/sections/Connectors/index.jsx
  src/components/organisms/sections/GitLabs/index.jsx
  src/components/organisms/sections/Page/index.jsx
  src/components/organisms/sections/Permissions/index.jsx
  src/components/organisms/sections/Pipelines/index.jsx
  src/components/organisms/sections/Project/index.jsx
  src/components/organisms/sections/User/index.jsx
  src/components/organisms/tabs/PageImprint/index.jsx
  src/components/organisms/tabs/PageOverview/index.jsx
  src/components/organisms/tabs/PageProjects/index.jsx
  src/components/organisms/tabs/PageUsers/index.jsx
  src/components/pages/LoginPage/index.jsx
  src/components/pages/index.js
  src/store/actions/authActions.js
  src/store/reducers/authReducer.js
  src/store/reducers/connectorReducer.js
  src/store/reducers/gitlabReducer.js
  src/store/reducers/pageReducer.js
  src/store/reducers/permissionReducer.js
  src/store/reducers/pipelineReducer.js
  src/store/reducers/rootReducer.js
  src/utilities/_base.scss
Labels: enhancement

#25 Improve pipelines aa1 to implement 1
  src/components/organisms/sections/Pipelines/index.jsx
  src/store/actions/pipelineActions.js
Labels: enhancement

#26 Improve permissions aa1 to implement 1
  src/components/atoms/AICheckbox/index.jsx
  src/components/atoms/index.js
  src/components/organisms/sections/Permissions/index.jsx
  src/store/actions/permissionActions.js
  src/store/reducers/permissionReducer.js
Labels: enhancement

#27 Improve connector aa1 to implement 1
  src/components/organisms/sections/Connectors/index.jsx
  src/store/actions/connectorActions.js
Labels: enhancement

#28 Improve gitlabs aa1 to implement 1
  src/components/organisms/sections/GitLabs/index.jsx
  src/store/actions/gitlabActions.js
Labels: enhancement

#29 Improve pages aa1 to implement 1
  src/components/organisms/index.js
  src/components/organisms/modals/ProjectModal/index.jsx
  src/components/organisms/modals/UserModal/index.jsx
  src/components/organisms/sections/Page/index.jsx
  src/components/organisms/tabs/PageProjects/index.jsx
  src/components/organisms/tabs/PageUsers/index.jsx
  src/components/pages/AdminPage/index.jsx
  src/store/actions/pageActions.js
  src/store/reducers/pageReducer.js
Labels: enhancement

#30 Add cleanup aa1 to implement 1
  src/components/organisms/index.js
  src/components/organisms/modals/GitLabModal/index.jsx
  src/components/organisms/sections/GitLabs/index.jsx
  src/store/actions/connectorActions.js
  src/store/actions/permissionActions.js
Labels: documentation, enhancement
